import Clientprovider from '@/components/Clientprovider'
import Login from '@/components/Login'
import { SessionProvider } from '@/components/SessionProvider'
import Sidebar from '@/components/Sidebar'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import '@/styles/globals.css'
import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session=await getServerSession(authOptions)
  // console.log(session)
  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {
            !session?
            (<Login />):
            (
            <div className='flex'>
              <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
                <Sidebar />
              </div>
              <Clientprovider />
          
              <div className='bg-[#353333] flex-1'>{children}</div>
            </div>
            )
          }
          
        </SessionProvider>
        
      </body>
    </html>
  )
}
